all:redis_tool.cpp
	clear
	clear
	g++ -c redis_tool.cpp -o redis_tool.o -std=c++17 -ggdb	-I../ \
	-I/home/dengmuyang/dolphin_server/thirdpart_dolphin/include \
	-L/home/dengmuyang/dolphin_server/thirdpart_dolphin/lib -levent -lhiredis \
	-I/home/dengmuyang/dolphin_server/thirdpart_dolphin/include/hiredis 